---
- name: 修改training用户的密码
  hosts: all
  gather_facts: no

  tasks:
    - name: 使用明文密码修改training用户密码
      ansible.builtin.user:
        name: training
        password: "{{ training_password | string | password_hash('sha512') }}"
        update_password: always  # 总是更新密码（即使与当前密码相同）
      when: training_password is defined
